import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@/services/clerk/components/ClerkProvider";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";


const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

const outfitMono = Outfit({
  variable: "--font-outfit-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en" suppressHydrationWarning
        className={`${outfitSans.variable} ${outfitMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableColorScheme disableTransitionOnChange>{children}
       <Toaster/>
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
